// Generates supabase/seed.sql from the shared demo catalog so the backend and the demo mode
// always have the same UUIDs, prices and stock. Usage: npm run db:seed:generate
import { readFileSync, writeFileSync } from 'node:fs';

const source = 'src/features/demo/data/fixtures/catalog.json';
const target = 'supabase/seed.sql';

const catalog = JSON.parse(readFileSync(source, 'utf8'));

const str = (value) => `'${String(value).replaceAll("'", "''")}'`;
const textArray = (values) => `array[${values.map(str).join(',')}]::text[]`;

const categoryRows = catalog.categories.map(
  (c) => `  (${str(c.id)}, ${str(c.slug)}, ${str(c.name)}, ${c.sortOrder})`,
);

const productRows = catalog.products.map(
  (p) =>
    `  (${str(p.id)}, ${str(p.slug)}, ${str(p.name)}, ${str(p.description)}, ${p.priceCents}, ${str(p.currency)}, ` +
    `${str(p.categoryId)}, ${textArray(p.imagePaths)}, ${p.stock}, ${p.isActive}, ${str(p.createdAt)})`,
);

const sql = `-- GENERATED by scripts/generate-seed.mjs from ${source}. Do not edit.
-- Demo catalog: same UUIDs, prices and stock as the demo mode. No users or orders on purpose.

insert into vitrina.categories (id, slug, name, sort_order) values
${categoryRows.join(',\n')}
on conflict (id) do nothing;

insert into vitrina.products (id, slug, name, description, price_cents, currency, category_id, image_paths, stock, is_active, created_at) values
${productRows.join(',\n')}
on conflict (id) do nothing;
`;

writeFileSync(target, sql);
console.log(
  `Wrote ${target} (${catalog.categories.length} categories, ${catalog.products.length} products)`,
);
